### ISSUE TITLE
Movement System

### ISSUE THREAD

**Issue by e1pupper** [letsbuilda/pyweek-2023-03#2]
This system would handle the player's movement, including dashing, double-jumping, and moving around the game environment. It would also handle collision detection and physics, ensuring that the player moves smoothly and fluidly through the game world.

First thing first since we will have different characters that move it would be nice to have a character class. This character class is just the sprite of the character, width and height, and collission Im pretty sure arcade has something built in for that.

`
class Character:
    """ Character boilerplate """
    def __init__(self, ...):
         """ Character init"""
`

Next thing is implementing WASD movement W for jump (player can jump again for double jump) S to duck (if double tapped S go down platform) A for strafe left D for strafe right.

We need to also make sure to use the sprite sheet to animate everything. (if there is art)

**Comment by e1pupper** [comment]
Also we want character states. That would make life easier. For example when player jumps the state is airborn.

**Comment by Anonymous4045** [comment]
I vote we also add in arrow controls, so right, left, up, down too, and spacebar for jump. Some players prefer arrows and some prefer wasd, so I think we can just implement both

**Comment by e1pupper** [comment]
>  I think we can just implement both

might be just better to do a settings page for it that way people around the world with different keyboard layouts can set there own to whatever.

**Comment by FieryIceStickie** [comment]
Finished since #15
