### ISSUE TITLE
Combat System

### ISSUE THREAD

**Issue by e1pupper** [letsbuilda/pyweek-2023-03#3]
The combat system would handle the player's attacks and defensive moves, including slicing and dicing, stealth kills, and throwing knives.

We want to design this in such a way where we can just slap the combat system onto any character we want.

The combat system is it's own class and the player attacking inputs is another class essentially just applying the logic for inputs.

The combat system should have 4 different attacks depending on the character state. Quick attack(fast attack that does a good amount of damage maybe some kind of chargeup so that it can become a heavy attack), steakth attack (if the player is not detected and is right upfront on the enemy and the enemy is not on sight with other people he can insta kill the enemy), Slice and dice(slice through enemies only when airborn so this would override the quick attack if chargeup is implemented would be cool to do extra damage and increase dash distance when released) and finally throwing knives the damage of the knife should depend on the velocity of the knife which allows the player to also charge up this attack or also throw multiple knives at once in slow motion.

**Comment by FieryIceStickie** [comment]
this is kinda dependent on the time slowdown system
