### ISSUE TITLE
Enemy AI System

### ISSUE THREAD

**Issue by e1pupper** [letsbuilda/pyweek-2023-03#4]
This system would handle the behavior and movement of enemy characters in the game. It would include logic for enemy pathfinding, awareness, and combat behavior. For example, enemies might move in patterns or patrol areas, become alerted when they hear a noise or see the player, and engage the player in combat when they get close enough. The system would also handle enemy attacks, including melee attacks and ranged attacks like throwing knives, and damage detection.

To make this easier we can raycast 3 lines infront of the enemy(top middle bottom) to check if there is a player, and also have a spherical hitbox that is significantly larger than the enemy itself and we can use that to detect the noise of the player.

**Comment by Anonymous4045** [comment]
I think I can make a better way for the noise than just a larger hitbox, but we'll see.
